#!/bin/bash

set -eu

: ${DUCT_OUTPUT_PREFIX:=.duct/run-logs/`date --iso-8601=sec`_$$}

export DUCT_OUTPUT_PREFIX

STATS_FILE="${DUCT_OUTPUT_PREFIX}.stats.json"

current_commit=$(git rev-parse HEAD)

"$@"

new_commit=$(git rev-parse HEAD)

if [ "$current_commit" != "$new_commit" ] && [ -e "$STATS_FILE" ]; then
	git notes add -m "$STATS_FILE" -F "$STATS_FILE"
fi
