version = 1

[[annotations]]
path = "src/con_duct/**"
SPDX-FileCopyrightText = [
    "2019-2021 brainlife",
    "2024-2026 Center for Open Neuroscience",
]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    ".autorc",
    ".github/**",
    ".gitignore",
    ".pre-commit-config.yaml",
    ".update-readme-help.py",
    "CHANGELOG.md",
    "CLAUDE.md",
    "CONTRIBUTING.rst",
    "MANIFEST.in",
    "README.md",
    "demo/**",
    "pyproject.toml",
    "test/**",
    "tox.ini",
]
SPDX-FileCopyrightText = "2024-2026 Center for Open Neuroscience"
SPDX-License-Identifier = "MIT"
